"""Contrato do adaptador; integração usa somente SAGEL_TEST_POSTGRES_DSN."""
import os
import sqlite3
import unittest
import uuid

import psycopg
from psycopg import sql

from sagel.database import BancoPostgres, LinhaPostgres, _comandos, _dialeto, adaptar_sql


class TestAdaptacaoSQL(unittest.TestCase):
    def test_binds_nao_alteram_literais_identificadores_e_comentarios(self):
        query = "SELECT ?, '?', \"?\", 'it''s ?', $$?$$, $tag$?$tag$ -- ?\n/* ? */ WHERE id=?"
        expected = "SELECT %s, '?', \"?\", 'it''s ?', $$?$$, $tag$?$tag$ -- ?\n/* ? */ WHERE id=%s"
        self.assertEqual(adaptar_sql(query), expected)

    def test_percentual_e_modulo_seguros_com_psycopg(self):
        self.assertEqual(adaptar_sql("SELECT ? % 3, '100%', '%s'"), "SELECT %s %% 3, '100%%', '%%s'")

    def test_scripts_preservam_ponto_virgula_em_literais_e_comentarios(self):
        statements = list(_comandos("SELECT ';'; -- ;\nSELECT $$;$$; /* ; /* ; */ */"))
        self.assertEqual(statements, ["SELECT ';'", '-- ;\nSELECT $$;$$'])

    def test_escape_string_postgres(self):
        self.assertEqual(adaptar_sql(r"SELECT E'a\'?b', ?"), r"SELECT E'a\'?b', %s")

    def test_ddl_preserva_64_bits_e_precisao_sqlite(self):
        result = _dialeto("CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, total INTEGER, valor REAL, nome TEXT DEFAULT 'INTEGER REAL')")
        self.assertIn('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', result)
        self.assertIn('total BIGINT, valor DOUBLE PRECISION', result)
        self.assertIn("DEFAULT 'INTEGER REAL'", result)

    def test_ignore_replace_conhecidos_e_recusa_replace_desconhecido(self):
        self.assertIn('ON CONFLICT DO NOTHING', _dialeto('INSERT OR IGNORE INTO permissoes VALUES(?,?,?)'))
        self.assertIn('valor=EXCLUDED.valor', _dialeto('INSERT OR REPLACE INTO configuracoes VALUES(?,?)'))
        self.assertIn('inicio=EXCLUDED.inicio', _dialeto('INSERT OR REPLACE INTO tentativas_login VALUES(?,?,?)'))
        with self.assertRaises(sqlite3.NotSupportedError):
            _dialeto('INSERT OR REPLACE INTO usuarios VALUES(?)')

    def test_max_escalar_sem_alterar_max_agregado(self):
        self.assertEqual(_dialeto('SELECT MAX(quilometragem,?), MAX(id) FROM frota_veiculos'),
                         'SELECT GREATEST(quilometragem,?), MAX(id) FROM frota_veiculos')

    def test_linha_aceita_nome_indice_fatia_dict_e_valores(self):
        row = LinhaPostgres(['ID', 'nome'], [12, 'Ana'])
        self.assertEqual(row[0], row['id'])
        self.assertEqual(row[-1], 'Ana')
        self.assertEqual(row[:], (12, 'Ana'))
        self.assertEqual(dict(row), {'ID': 12, 'nome': 'Ana'})
        self.assertEqual(list(row), [12, 'Ana'])
        with self.assertRaises(IndexError):
            _ = row['ausente']


@unittest.skipUnless(os.environ.get('SAGEL_TEST_POSTGRES_DSN'), 'PostgreSQL temporário não configurado')
class TestBancoPostgres(unittest.TestCase):
    def setUp(self):
        self.raw = psycopg.connect(os.environ['SAGEL_TEST_POSTGRES_DSN'])
        self.schema = 'sagel_adapter_test_' + uuid.uuid4().hex
        self.raw.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(self.schema)))
        self.raw.execute(sql.SQL('SET search_path TO {}').format(sql.Identifier(self.schema)))
        self.raw.commit()
        self.db = BancoPostgres(self.raw)

    def tearDown(self):
        self.raw.rollback()
        self.raw.execute(sql.SQL('DROP SCHEMA {} CASCADE').format(sql.Identifier(self.schema)))
        self.raw.commit()
        self.raw.close()

    def test_lastrowid_linhas_nomes_indices_e_precisao(self):
        self.db.executescript('CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, valor REAL, total INTEGER);')
        result = self.db.execute('INSERT INTO itens(nome,valor,total) VALUES(?,?,?)', ('Ana?', 0.123456789123, 9_000_000_000))
        self.assertEqual(result.lastrowid, 1)
        self.assertEqual(result.rowcount, 1)
        self.assertIsNone(result.fetchone())
        row = self.db.execute('SELECT * FROM itens').fetchone()
        self.assertEqual(row[0], 1)
        self.assertEqual(row['nome'], 'Ana?')
        self.assertEqual(row['total'], 9_000_000_000)
        self.assertAlmostEqual(row['valor'], 0.123456789123, places=12)

    def test_percentuais_parametrizados_e_literais(self):
        row = self.db.execute("SELECT ? AS texto, '100%' AS literal, ? % 3 AS resto", ('50%?', 8)).fetchone()
        self.assertEqual(tuple(row), ('50%?', '100%', 2))
        self.assertEqual(self.db.execute("SELECT '100%' AS literal").fetchone()[0], '100%')

    def test_amplia_tipos_existentes_sem_alterar_valores_e_reverte_com_rollback(self):
        self.raw.execute('CREATE TABLE cp_itens(id bigserial PRIMARY KEY,quantidade real,total integer)')
        self.raw.execute('INSERT INTO cp_itens(quantidade,total) VALUES(1.25,200)')
        self.raw.commit()
        self.db.adequar_tipos()
        self.db.execute('UPDATE cp_itens SET total=?', (9_000_000_000,))
        self.assertEqual(tuple(self.db.execute('SELECT quantidade,total FROM cp_itens').fetchone()), (1.25, 9_000_000_000))
        self.db.rollback()
        self.assertEqual(tuple(self.raw.execute('SELECT quantidade,total FROM cp_itens').fetchone()), (1.25, 200))
        self.assertEqual(self.raw.execute("SELECT data_type FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='cp_itens' AND column_name='total'").fetchone()[0], 'integer')

    def test_savepoint_recupera_integridade_sem_perder_inserts_anteriores(self):
        self.db.execute('CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT UNIQUE)')
        self.db.execute('INSERT INTO itens(nome) VALUES(?)', ('Ana',))
        with self.assertRaises(sqlite3.IntegrityError) as captured:
            self.db.execute('INSERT INTO itens(nome) VALUES(?)', ('Ana',))
        self.assertNotIn('Ana', str(captured.exception))
        self.assertEqual(captured.exception.sqlstate, '23505')
        self.db.execute('INSERT INTO itens(nome) VALUES(?)', ('Bia',))
        self.assertEqual(self.db.execute('SELECT COUNT(*) FROM itens').fetchone()[0], 2)
        self.db.commit()
        self.assertEqual(self.db.execute('SELECT COUNT(*) FROM itens').fetchone()[0], 2)

    def test_script_atomico_e_sem_commit_implicito(self):
        self.db.execute('CREATE TABLE anterior(nome TEXT)')
        self.db.execute('INSERT INTO anterior VALUES(?)', ('preservado',))
        with self.assertRaises(sqlite3.Error):
            self.db.executescript("CREATE TABLE parcial(nome TEXT); INSERT INTO inexistente VALUES('erro');")
        self.assertEqual(self.db.execute("SELECT to_regclass('parcial')").fetchone()[0], None)
        self.assertEqual(self.db.execute('SELECT COUNT(*) FROM anterior').fetchone()[0], 1)
        self.db.rollback()
        self.assertEqual(self.db.execute("SELECT to_regclass('anterior')").fetchone()[0], None)

    def test_upserts_com_e_sem_id_retornam_id_correto(self):
        self.db.executescript('''CREATE TABLE configuracoes(chave TEXT PRIMARY KEY, valor TEXT NOT NULL);
            CREATE TABLE tentativas_login(chave TEXT PRIMARY KEY, quantidade INTEGER, inicio TEXT);
            CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT UNIQUE);''')
        self.db.execute('INSERT OR REPLACE INTO configuracoes VALUES(?,?)', ('tema', 'a'))
        result = self.db.execute('INSERT OR REPLACE INTO configuracoes VALUES(?,?)', ('tema', 'b'))
        self.assertIsNone(result.lastrowid)
        self.assertEqual(self.db.execute('SELECT valor FROM configuracoes').fetchone()[0], 'b')
        self.db.execute('INSERT OR REPLACE INTO tentativas_login VALUES(?,?,?)', ('chave', 4, 'antes'))
        self.db.execute('INSERT OR REPLACE INTO tentativas_login VALUES(?,?,?)', ('chave', 1, 'depois'))
        self.assertEqual(tuple(self.db.execute('SELECT quantidade,inicio FROM tentativas_login').fetchone()), (1, 'depois'))
        self.db.execute('INSERT INTO itens(nome) VALUES(?)', ('Ana',))
        ignored = self.db.execute('INSERT OR IGNORE INTO itens(nome) VALUES(?)', ('Ana',))
        self.assertIsNone(ignored.lastrowid)
        self.assertEqual(ignored.rowcount, 0)

    def test_executemany_e_rowcount(self):
        self.db.execute('CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT)')
        result = self.db.executemany('INSERT INTO itens(nome) VALUES(?)', [('a',), ('b',)])
        self.assertEqual(result.rowcount, 2)
        self.assertIsNone(result.lastrowid)
        result = self.db.execute('UPDATE itens SET nome=? WHERE id=?', ('c', 1))
        self.assertEqual(result.rowcount, 1)
        rows = list(self.db.execute('SELECT nome FROM itens ORDER BY id'))
        self.assertEqual([row['nome'] for row in rows], ['c', 'b'])

    def test_pragma_e_recusa_comandos_nao_suportados(self):
        self.db.execute('CREATE TABLE itens(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL)')
        rows = self.db.execute('PRAGMA table_info(itens)').fetchall()
        self.assertEqual([row['name'] for row in rows], ['id', 'nome'])
        self.assertEqual(rows[0]['pk'], 1)
        self.assertEqual(rows[1]['notnull'], 1)
        self.db.execute('PRAGMA journal_mode=WAL')
        self.db.execute('PRAGMA foreign_keys=ON')
        with self.assertRaises(sqlite3.NotSupportedError):
            self.db.execute('PRAGMA foreign_keys=OFF')
        with self.assertRaises(sqlite3.ProgrammingError):
            self.db.execute('SELECT 1; SELECT 2')
        self.assertEqual(self.db.execute('SELECT 1').fetchone()[0], 1)

    def test_begin_immediate_preserva_transacao_aberta_e_lock_ate_commit(self):
        self.db.execute('CREATE TABLE itens(nome TEXT)')
        self.db.execute('INSERT INTO itens VALUES(?)', ('pendente',))
        self.db.execute('BEGIN IMMEDIATE')
        other = psycopg.connect(os.environ['SAGEL_TEST_POSTGRES_DSN'])
        try:
            self.assertFalse(other.execute('SELECT pg_try_advisory_xact_lock(%s)', (BancoPostgres.LOCK_ESCRITA,)).fetchone()[0])
            other.rollback()
            self.db.rollback()
            self.assertTrue(other.execute('SELECT pg_try_advisory_xact_lock(%s)', (BancoPostgres.LOCK_ESCRITA,)).fetchone()[0])
            self.assertIsNone(self.db.execute("SELECT to_regclass('itens')").fetchone()[0])
        finally:
            other.close()


if __name__ == '__main__':
    unittest.main()
