"""Ponte limitada entre as consultas legadas da SAGEL e psycopg 3.

Não é um tradutor geral de SQLite. A aplicação mantém transações explícitas;
cada comando usa um savepoint para que os handlers legados de sqlite3.Error
continuem podendo recuperar erros sem inutilizar a transação PostgreSQL.
"""
from collections.abc import Mapping
from contextlib import contextmanager
import itertools
import re
import sqlite3

import psycopg
from psycopg.rows import tuple_row
from psycopg import sql as pgsql


def _partes_sql(sql):
    """Separa código, literais, identificadores citados e comentários."""
    start = index = 0
    size = len(sql)
    while index < size:
        end = None
        quote = sql[index]
        if quote in "'\"`":
            end = index + 1
            escaped = quote == "'" and index > 0 and sql[index - 1] in 'eE' and (
                index < 2 or not (sql[index - 2].isalnum() or sql[index - 2] == '_'))
            while end < size:
                if escaped and sql[end] == '\\':
                    end += 2
                elif sql[end] == quote:
                    if end + 1 < size and sql[end + 1] == quote:
                        end += 2
                    else:
                        end += 1
                        break
                else:
                    end += 1
        elif sql.startswith('--', index):
            end = sql.find('\n', index)
            end = size if end < 0 else end + 1
        elif sql.startswith('/*', index):
            end, depth = index + 2, 1
            while end < size and depth:
                if sql.startswith('/*', end):
                    depth += 1
                    end += 2
                elif sql.startswith('*/', end):
                    depth -= 1
                    end += 2
                else:
                    end += 1
        elif quote == '$':
            tag = re.match(r'\$(?:[A-Za-z_][A-Za-z_0-9]*)?\$', sql[index:])
            if tag:
                stop = sql.find(tag[0], index + len(tag[0]))
                end = size if stop < 0 else stop + len(tag[0])
        if end is not None:
            if start < index:
                yield True, sql[start:index]
            yield False, sql[index:end]
            start = index = end
        else:
            index += 1
    if start < size:
        yield True, sql[start:]


def _codigo(sql):
    return ''.join(part if code else ' ' * len(part) for code, part in _partes_sql(sql))


def _sub_codigo(sql, pattern, replacement):
    return ''.join(re.sub(pattern, replacement, part, flags=re.I) if code else part
                   for code, part in _partes_sql(sql))


def _comandos(sql):
    pending = ''
    for code, part in _partes_sql(sql):
        if not code:
            pending += part
            continue
        segments = part.split(';')
        for segment in segments[:-1]:
            pending += segment
            if _codigo(pending).strip():
                yield pending.strip()
            pending = ''
        pending += segments[-1]
    if _codigo(pending).strip():
        yield pending.strip()


def adaptar_sql(sql):
    """Converte binds fora de literais e escapa % para parâmetros psycopg.

    O resultado deve ser executado com uma sequência de parâmetros, inclusive
    a tupla vazia. Literais e comentários nunca recebem substituição de '?'.
    """
    return ''.join(part.replace('%', '%%').replace('?', '%s') if code
                   else part.replace('%', '%%') for code, part in _partes_sql(sql))


def _anexar_clausula(sql, clause):
    returning = re.search(r'\bRETURNING\b', _codigo(sql), re.I)
    if returning:
        return sql[:returning.start()].rstrip() + '\n' + clause + '\n' + sql[returning.start():]
    # Uma linha nova evita colocar a cláusula dentro de um comentário '--'.
    return sql + '\n' + clause


def _dialeto(sql):
    code = _codigo(sql)
    if re.match(r'\s*(?:CREATE\s+TABLE|ALTER\s+TABLE)\b', code, re.I):
        sql = _sub_codigo(sql, r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
                          'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        sql = _sub_codigo(sql, r'\bINTEGER\b', 'BIGINT')
        sql = _sub_codigo(sql, r'\bREAL\b', 'DOUBLE PRECISION')
    sql = _sub_codigo(sql, r'\bMAX\s*\(\s*quilometragem\s*,\s*\?\s*\)',
                      'GREATEST(quilometragem,?)')
    insert = re.match(r'\s*INSERT\s+OR\s+(IGNORE|REPLACE)\s+INTO\s+([a-z_][a-z_0-9]*)\b',
                      _codigo(sql), re.I)
    if insert:
        mode, table = insert.group(1).upper(), insert.group(2).lower()
        sql = _sub_codigo(sql, r'\bINSERT\s+OR\s+(?:IGNORE|REPLACE)\s+INTO\b', 'INSERT INTO')
        if mode == 'IGNORE':
            sql = _anexar_clausula(sql, 'ON CONFLICT DO NOTHING')
        else:
            updates = {'configuracoes': 'valor=EXCLUDED.valor',
                       'tentativas_login': 'quantidade=EXCLUDED.quantidade,inicio=EXCLUDED.inicio'}
            if table not in updates:
                raise sqlite3.NotSupportedError('INSERT OR REPLACE exige uma regra explícita para esta tabela.')
            sql = _anexar_clausula(sql, 'ON CONFLICT (chave) DO UPDATE SET ' + updates[table])
    return sql


class LinhaPostgres:
    """Acesso sqlite3.Row: nomes sem distinção de caixa, índices e valores."""
    def __init__(self, names, values):
        self._names, self._values = tuple(names), tuple(values)

    def keys(self):
        return list(self._names)

    def __getitem__(self, key):
        if isinstance(key, str):
            for index, name in enumerate(self._names):
                if name.lower() == key.lower():
                    return self._values[index]
            raise IndexError('No item with that key')
        return self._values[key]

    def __len__(self):
        return len(self._values)

    def __iter__(self):
        return iter(self._values)


class CursorPostgres:
    def __init__(self, cursor=None, *, lastrowid=None, rowcount=None):
        self._cursor = cursor
        self.lastrowid = lastrowid
        self.rowcount = cursor.rowcount if rowcount is None and cursor is not None else (
            -1 if rowcount is None else rowcount)
        self.description = cursor.description if cursor is not None else None

    def _linha(self, values):
        if values is None:
            return None
        names = [getattr(column, 'name', column[0]) for column in self.description]
        if isinstance(values, Mapping):
            values = [values[name] for name in names]
        return LinhaPostgres(names, values)

    def fetchone(self):
        if self._cursor is None or self.description is None:
            return None
        return self._linha(self._cursor.fetchone())

    def fetchmany(self, size=1):
        result = []
        for _ in range(size):
            row = self.fetchone()
            if row is None:
                break
            result.append(row)
        return result

    def fetchall(self):
        return list(self)

    def __iter__(self):
        return self

    def __next__(self):
        row = self.fetchone()
        if row is None:
            raise StopIteration
        return row

    def close(self):
        if self._cursor is not None:
            self._cursor.close()


def _erro_legado(error):
    if isinstance(error, psycopg.IntegrityError):
        result = sqlite3.IntegrityError('O registro viola uma regra de integridade do banco de dados.')
    elif isinstance(error, psycopg.OperationalError):
        result = sqlite3.OperationalError('Não foi possível concluir a operação no banco de dados.')
    elif isinstance(error, psycopg.ProgrammingError):
        result = sqlite3.ProgrammingError('A consulta não pôde ser executada pelo banco de dados.')
    else:
        result = sqlite3.DatabaseError('Falha na operação do banco de dados.')
    # SQLSTATE é diagnóstico seguro; mensagens PostgreSQL podem conter dados.
    result.sqlstate = error.sqlstate
    return result


class BancoPostgres:
    # Lock transacional compartilhado pelas operações legadas BEGIN IMMEDIATE.
    # Preserva sua serialização enquanto as rotas recebem locks mais específicos.
    LOCK_ESCRITA = 1396787013
    TABELAS_SAGEL = (
        'usuarios', 'avisos', 'tarefas', 'documentos', 'permissoes', 'configuracoes', 'auditoria',
        'recuperacoes', 'tentativas_login', 'frota_veiculos', 'frota_manutencoes',
        'frota_manutencao_historico', 'frota_documentos', 'frota_utilizacoes', 'combustivel_movimentos',
        'epi_itens', 'epi_movimentos', 'ti_equipamentos', 'ti_equipamento_historico', 'ti_chamados',
        'ti_chamado_historico', 'ti_chamado_anexos', 'ti_notificacoes', 'cp_solicitacoes', 'cp_itens',
        'cp_fornecedores', 'cp_cotacoes', 'cp_cotacao_itens', 'cp_pedidos', 'cp_historico',
        'gd_documentos', 'gd_versoes', 'gd_acessos', 'cadastros_pendentes', 'cadastro_envios')

    def __init__(self, conexao):
        if conexao.autocommit:
            raise ValueError('BancoPostgres exige autocommit desativado.')
        self.conexao = conexao
        self._savepoints = itertools.count(1)
        self._tabelas_id = {}

    def _raw(self, sql, parameters=None):
        cursor = self.conexao.cursor(row_factory=tuple_row)
        try:
            cursor.execute(sql, parameters)
        except BaseException:
            cursor.close()
            raise
        return cursor

    def _controle(self, sql):
        self._raw(sql).close()

    @contextmanager
    def _atomico(self):
        name = 'sagel_stmt_' + str(next(self._savepoints))
        try:
            self._controle('SAVEPOINT ' + name)
        except psycopg.Error as error:
            raise _erro_legado(error) from None
        try:
            yield
        except BaseException as error:
            try:
                self._controle('ROLLBACK TO SAVEPOINT ' + name)
                self._controle('RELEASE SAVEPOINT ' + name)
            except psycopg.Error:
                pass  # Conexão interrompida: preservar a causa original sanitizada.
            self._tabelas_id.clear()
            if isinstance(error, psycopg.Error):
                raise _erro_legado(error) from None
            raise
        else:
            try:
                self._controle('RELEASE SAVEPOINT ' + name)
            except psycopg.Error as error:
                raise _erro_legado(error) from None

    def _tem_id(self, table):
        if table not in self._tabelas_id:
            cursor = self._raw("""SELECT EXISTS (
                SELECT 1 FROM pg_catalog.pg_attribute
                WHERE attrelid=to_regclass(%s) AND attname='id'
                  AND attnum>0 AND NOT attisdropped)""", (table,))
            try:
                self._tabelas_id[table] = bool(cursor.fetchone()[0])
            finally:
                cursor.close()
        return self._tabelas_id[table]

    def _executar(self, sql, parametros):
        statements = list(_comandos(sql))
        if len(statements) != 1:
            raise sqlite3.ProgrammingError('execute aceita exatamente um comando SQL.')
        sql = statements[0]
        code = _codigo(sql).strip()
        if re.fullmatch(r'BEGIN\s+IMMEDIATE(?:\s+TRANSACTION)?', code, re.I):
            if parametros:
                raise sqlite3.ProgrammingError('BEGIN IMMEDIATE não aceita parâmetros.')
            self._raw('SELECT pg_advisory_xact_lock(%s)', (self.LOCK_ESCRITA,)).close()
            return CursorPostgres()
        if re.match(r'(?:BEGIN|COMMIT|END|ROLLBACK|SAVEPOINT|RELEASE)\b', code, re.I):
            raise sqlite3.NotSupportedError('Use os métodos commit e rollback para encerrar transações.')
        if re.match(r'PRAGMA\b', code, re.I):
            table = re.fullmatch(r'PRAGMA\s+table_info\s*\(\s*([a-z_][a-z_0-9]*)\s*\)', code, re.I)
            if table:
                return CursorPostgres(self._raw("""SELECT ordinal_position-1 AS cid,
                    column_name AS name, data_type AS type,
                    CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS "notnull",
                    column_default AS dflt_value,
                    CASE WHEN EXISTS (
                        SELECT 1 FROM information_schema.table_constraints t
                        JOIN information_schema.key_column_usage k
                          ON t.constraint_catalog=k.constraint_catalog
                         AND t.constraint_schema=k.constraint_schema
                         AND t.constraint_name=k.constraint_name
                        WHERE t.constraint_type='PRIMARY KEY'
                          AND t.table_schema=c.table_schema AND t.table_name=c.table_name
                          AND k.column_name=c.column_name) THEN 1 ELSE 0 END AS pk
                    FROM information_schema.columns c
                    WHERE table_schema=current_schema() AND table_name=%s
                    ORDER BY ordinal_position""", (table[1].lower(),)))
            if re.fullmatch(r'PRAGMA\s+(?:journal_mode\s*=\s*WAL|foreign_keys\s*=\s*(?:ON|1))', code, re.I):
                return CursorPostgres()
            raise sqlite3.NotSupportedError('Este PRAGMA não é suportado pelo PostgreSQL.')
        sql = _dialeto(sql)
        code = _codigo(sql)
        insert = re.match(r'\s*INSERT\s+INTO\s+([a-z_][a-z_0-9]*)\b', code, re.I)
        generated_id = bool(insert and not re.search(r'\bRETURNING\b', code, re.I)
                            and self._tem_id(insert[1].lower()))
        if generated_id:
            sql = _anexar_clausula(sql, 'RETURNING id')
        cursor = self._raw(adaptar_sql(sql), parametros)
        if re.match(r'\s*(?:CREATE|ALTER|DROP)\b', code, re.I):
            self._tabelas_id.clear()
        if generated_id:
            rows, count = cursor.fetchall(), cursor.rowcount
            cursor.close()
            return CursorPostgres(lastrowid=rows[-1][0] if rows else None, rowcount=count)
        return CursorPostgres(cursor)

    def execute(self, sql, parametros=()):
        with self._atomico():
            return self._executar(sql, parametros)

    def executemany(self, sql, sequencia_parametros):
        count = 0
        with self._atomico():
            for parametros in sequencia_parametros:
                cursor = self._executar(sql, parametros)
                count += max(cursor.rowcount, 0)
                cursor.close()
        return CursorPostgres(rowcount=count)

    def executescript(self, sql):
        # Não reproduz o commit implícito de sqlite3.executescript: schema e seeds
        # permanecem atômicos com a transação aberta pelo chamador.
        with self._atomico():
            for statement in _comandos(sql):
                self._executar(statement, ()).close()
        return CursorPostgres()

    def commit(self):
        try:
            self.conexao.commit()
        except psycopg.Error as error:
            raise _erro_legado(error) from None

    def adequar_tipos(self):
        """Amplia tipos da primeira importação sem reduzir precisão ou limites.

        A alteração faz parte da transação de inicialização e tem espera limitada
        por locks. Somente tabelas conhecidas da SAGEL são consideradas.
        """
        with self._atomico():
            self._controle("SET LOCAL lock_timeout='5s'")
            self._raw("SELECT pg_advisory_xact_lock(%s)", (self.LOCK_ESCRITA,)).close()
            cursor = self._raw("""SELECT table_name,column_name,data_type
                FROM information_schema.columns WHERE table_schema=current_schema()
                AND table_name=ANY(%s) AND data_type IN ('integer','real')
                ORDER BY table_name,ordinal_position""", (list(self.TABELAS_SAGEL),))
            columns = cursor.fetchall()
            cursor.close()
            if not columns:
                return
            self._controle("SET LOCAL lock_timeout='5s'")
            grouped = {}
            for table, column, datatype in columns:
                target = 'BIGINT' if datatype == 'integer' else 'DOUBLE PRECISION'
                grouped.setdefault(table, []).append(pgsql.SQL('ALTER COLUMN {} TYPE {}').format(
                    pgsql.Identifier(column), pgsql.SQL(target)))
            for table, changes in grouped.items():
                self._raw(pgsql.SQL('ALTER TABLE {} {}').format(
                    pgsql.Identifier(table), pgsql.SQL(', ').join(changes))).close()

    def rollback(self):
        self._tabelas_id.clear()
        try:
            self.conexao.rollback()
        except psycopg.Error as error:
            raise _erro_legado(error) from None

    def close(self):
        self.conexao.close()
